// <auto-generated />
using DL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220502113647_AddCompaniesMigration")]
    partial class AddCompaniesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DL.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Flat")
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<int>("House")
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Flat = 20,
                            House = 31,
                            Street = "Толстого"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Flat = 30,
                            House = 20,
                            Street = "Аэродромная"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            Flat = 100,
                            House = 13,
                            Street = "Воронянского"
                        });
                });

            modelBuilder.Entity("DL.Models.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microdoft"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NVIDIA"
                        });
                });

            modelBuilder.Entity("DL.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Научно-исследовательский отдел"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отдел технического контроля"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Конструкторский отдел"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Отдел изобретательства и патентирования"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Отдел маркетинговых исследований"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Инструментальный отдел"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Отдел главного технолога"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Отдел автоматизации"
                        });
                });

            modelBuilder.Entity("DL.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("SerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompaniesId = 1,
                            DepartmentId = 1,
                            Name = "Александр",
                            Patronymic = "Генадьевич",
                            PositionId = 1,
                            SerName = "Моркович",
                            Telephone = "29 134-56-89"
                        },
                        new
                        {
                            Id = 2,
                            CompaniesId = 2,
                            DepartmentId = 3,
                            Name = "Дмитрий",
                            Patronymic = "Викторович",
                            PositionId = 5,
                            SerName = "Шишко",
                            Telephone = "29 456-74-13"
                        },
                        new
                        {
                            Id = 3,
                            CompaniesId = 2,
                            DepartmentId = 5,
                            Name = "Анатолий",
                            Patronymic = "Витальевич",
                            PositionId = 6,
                            SerName = "Гаврилов",
                            Telephone = "29 117-36-78"
                        });
                });

            modelBuilder.Entity("DL.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Главный конструктор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Заведующий лабораторией"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Конструктор"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Лаборант"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Начальник отдела ИТ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Системный администратор"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Старший программист"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Программист"
                        });
                });

            modelBuilder.Entity("DL.Models.Address", b =>
                {
                    b.HasOne("DL.Models.Employee", "Employee")
                        .WithOne("Address")
                        .HasForeignKey("DL.Models.Address", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DL.Models.Employee", b =>
                {
                    b.HasOne("DL.Models.Companies", "Companies")
                        .WithMany("Employees")
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DL.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DL.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DL.Models.Companies", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DL.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DL.Models.Employee", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("DL.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
